### ISSUE TITLE
read_utils.py revert_bam_picard fails with unrecognized option

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-core#7]
Error output:
```
TypeError: main_revert_bam_picard() got an unexpected keyword argument 'do_not_sanitize'
```
The `revert_bam_picard` entry point in read_utils.py is [decorated with an argument](https://github.com/broadinstitute/viral-core/blob/master/read_utils.py#L190) that tools/picard.py doesn't understand. I'm guessing I forgot something from the viral-ngs to viral-core porting, but it reminds me that we're missing a unit test on this too.

**Comment by dpark01** [comment]
@tomkinsc is the right thing to do here to delete that line that adds the argument, or add functionality to the tool class?

**Comment by tomkinsc** [comment]
Looks like this issue is present in viral-ngs as well. Let me take a look and refresh my memory.
